version: '3.7'

services:

  journal-frontend:
    build:
      context: ./journal-frontend
      dockerfile: Dockerfile.prod
    command: npm run build
    depends_on:
      - journal-backend
    ports: 
      - 3000:3000
    volumes:
      - ./journal-frontend:/journal-frontend:rw
      - ./journal-frontend/front_dist:/journal-frontend/front_dist:rw
      - /journal-frontend/node_modules
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true

  journal-backend:
    build:
      context: ./journal-backend
      dockerfile: Dockerfile
    depends_on:
      - journal-db
    ports: 
      - 3010:3010
    restart: always
    command: nodemon app.js
    volumes:
      - ./journal-backend:/journal-backend:rw
      - ./journal-backend/dist:/journal-backend/dist:rw
      - /journal-backend/node_modules
    environment:
      JOURNAL_DB_USERNAME: "${JOURNAL_DB_USERNAME}"
      JOURNAL_DB_PASSWORD: "${JOURNAL_DB_PASSWORD}"
      JOURNAL_DB_DATABASE: "${JOURNAL_DB_DATABASE}"
      JOURNAL_JWT_SECRET: "${JOURNAL_JWT_SECRET}"
      JOURNAL_DB_SERVICE_NAME: "journal-db"
    
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_DATABASE: "${JOURNAL_DB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${JOURNAL_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${JOURNAL_DB_PASSWORD}"
    logging:
      driver: "none"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
      - frontend
      - portfolio
      - quiz
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/crontab.txt:/crontab.txt
      - ./certs/conf:/etc/letsencrypt
      - ./journal-frontend/front_dist:/front_dist
    # logging:
      # driver: "none"

volumes:
  mongodb_data_container: