version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/initial/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/crontab.txt:/crontab.txt
      - ./frontend/dist:/dist
      - ./certs/conf:/etc/letsencrypt
      - ./nginx/initial/html:/usr/share/nginx/html